name: ci
on:
  push:
    paths-ignore: ["**.md"]
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.4'
      - 
        name: Test with the Go CLI
        run: go test -v